ClassAssignmentApp/Controllers/ClassSessionMVCController.cs
using Azure;
using ClassAssignmentApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace ClassAssignmentApp.Controllers
{
    public class ClassSessionMVCController : Controller
    {
        Uri baseAddress = new Uri("https://localhost:7008/api");

        private readonly HttpClient _client;

        public ClassSessionMVCController()
        {
            _client = new HttpClient();
            _client.BaseAddress = baseAddress;
        }

        [HttpGet]
        public IActionResult ClassSessionsIndex(int? InstructorID, int? ClassRoomID, int? CourseID, string? WeekDay,
            int? BuildingNumber, string? ScreenMessage, string? ErrorMessage)
        {
            ClassSessionMVMaint ClassSessionMV = new ClassSessionMVMaint();
            if (InstructorID != null) ClassSessionMV.InstructorID = (int)InstructorID;
            if (ClassRoomID != null) ClassSessionMV.ClassRoomID = (int)ClassRoomID;
            if (CourseID != null) ClassSessionMV.CourseID = (int)CourseID;
            if (WeekDay != null) ClassSessionMV.WeekDay = (string)WeekDay;
            if (BuildingNumber != null) ClassSessionMV.BuildingNumber = (int)BuildingNumber;

            GetAllLists(ClassSessionMV);
            ClassSessionMV.InstructorSessions = ReturnBlankWorkingSchedule();
            ClassSessionMV.ClassRoomSessions = ReturnBlankWorkingSchedule();

            if (InstructorID != null && ClassRoomID != null && CourseID != null
                && WeekDay != null && BuildingNumber != null)
            {
                RefreshScreen(ClassSessionMV);
            }

            if (ErrorMessage != null)
            {
                ClassSessionMV.ErrorMessage = (string)ErrorMessage;
                ClassSessionMV.ErrorCondition = true;
                ClassSessionMV.ShowForInput = true;
                ClassSessionMV.ShowInstructorSchedule = true;
                ClassSessionMV.ShowRoomSchedule = true;
                return View(ClassSessionMV);
            }

            return View(ClassSessionMV);
        }

        [HttpGet]
        public IActionResult StudentSessionsIndex(int? StudentID, int? CourseID,string? ScreenMessage, string? ErrorMessage)
        {
            StudentSessionMVMaint StudentSessionMV = new StudentSessionMVMaint();

            if (ScreenMessage != null && ScreenMessage == "Course Added")
            {
                CourseID = 0;
                StudentSessionMV.CourseID = 0;
                StudentSessionMV.ShowCourseSchedule = false;
            }

            if (StudentID != null) StudentSessionMV.StudentID = (int)StudentID;
            if (CourseID != null) StudentSessionMV.CourseID = (int)CourseID;

            GetAllStudentLists(StudentSessionMV);

            StudentSessionMV.StudentSessions = ReturnBlankWorkingSchedule();
            StudentSessionMV.CourseSessions = ReturnBlankWorkingSchedule();
            StudentSessionMV.CourseOfferings = ReturnBlankCourseOfferings();

            //if (StudentID != null && CourseID != null)
            //    RefreshStudentScreen(StudentSessionMV);

            if (StudentID != null)
                RefreshStudentScreen(StudentSessionMV);

            if (ErrorMessage != null)
            {
                StudentSessionMV.ErrorMessage = (string)ErrorMessage;
                StudentSessionMV.ShowScreenMessage = true;
            }

            return View(StudentSessionMV);
        }

        [HttpPost]
        public IActionResult ClassSessionsIndex(ClassSessionMVMaint ClassSessionMV, string? command)
        {
            ClassSessionMV.ShowScreenMessage = false;
            RefreshScreen(ClassSessionMV);

            if (command != null)
            {
                string FullCommand = command;
            }

            switch (command)
            {
                case "NewEntry":
                    if (ClassSessionMV.StartTime == null || ClassSessionMV.EndTime == null)
                    {
                        ClassSessionMV.ErrorCondition = true;
                        ClassSessionMV.ErrorMessage = "Start and End Times are required";
                        return View(ClassSessionMV);
                    }

                    if (ClassSessionMV.StartTime > ClassSessionMV.EndTime)
                    {
                        ClassSessionMV.ErrorCondition = true;
                        ClassSessionMV.ErrorMessage = "Start Time must be before End Time";
                        return View(ClassSessionMV);
                    }

                    if (ClassSessionMV.InstructorID == null || ClassSessionMV.InstructorID < 1)
                    {
                        ClassSessionMV.ErrorCondition = true;
                        ClassSessionMV.ErrorMessage = "Instructor ID is missing";
                        return View(ClassSessionMV);
                    }

                    if (ClassSessionMV.WeekDay == null || ClassSessionMV.WeekDay == "")
                    {
                        ClassSessionMV.ErrorCondition = true;
                        ClassSessionMV.ErrorMessage = "WeekDay is missing";
                        return View(ClassSessionMV);
                    }

                    string InstructorCallSequence = _client.BaseAddress + "/ClassSession/"
                        + ClassSessionMV.InstructorID.ToString() + "/"
                        + ClassSessionMV.WeekDay + "/"
                        + ClassSessionMV.StartTime.ToString() + "/"
                        + ClassSessionMV.EndTime.ToString() + "/Instructor";
                    HttpResponseMessage InstructorConflicts = _client.GetAsync(InstructorCallSequence).Result;

                    string ClassRoomCallSequence = _client.BaseAddress + "/ClassSession/"
                        + ClassSessionMV.ClassRoomID.ToString() + "/"
                        + ClassSessionMV.WeekDay + "/"
                        + ClassSessionMV.StartTime.ToString() + "/"
                        + ClassSessionMV.EndTime.ToString() + "/ClassRoom";
                    HttpResponseMessage ClassRoomConflicts = _client.GetAsync(ClassRoomCallSequence).Result;


                    if (InstructorConflicts.IsSuccessStatusCode && ClassRoomConflicts.IsSuccessStatusCode)
                    {
                        //var dataList = InstructorConflicts.Content.ReadAsAsync<IList<WorkingDailyConflicts>>();
                        //List<WorkingDailyConflicts> ConflictList = dataList.Result.ToList();

                        //if (ConflictList.Count == 1)
                        //{
                        //    ClassSessionMV.ErrorCondition = true;
                        //    ClassSessionMV.ErrorMessage = "Conflicts with instructor session: "
                        //        + ConflictList[0].StartTime.ToString() + " - " +
                        //        ConflictList[0].EndTime.ToString();
                        //    return View(ClassSessionMV);
                        //}
                        //else if (ConflictList.Count > 1)
                        //    {
                        //    ClassSessionMV.ErrorCondition = true;
                        //    ClassSessionMV.ErrorMessage = "Multiple session conflicts";
                        //     return View(ClassSessionMV);
                        //}
                        //----------------------------------------------------------------------
                        var InstructorDataList = InstructorConflicts.Content.ReadAsAsync<IList<WorkingDailyConflicts>>();
                        List<WorkingDailyConflicts> InstructorConflictList = InstructorDataList.Result.ToList();

                        var ClassRoomDataList = ClassRoomConflicts.Content.ReadAsAsync<IList<WorkingDailyConflicts>>();
                        List<WorkingDailyConflicts> ClassRoomConflictList = ClassRoomDataList.Result.ToList();

                        if (InstructorConflictList.Count > 0 || ClassRoomConflictList.Count > 0)
                        { //At least one conflict - either Instructor or Classroom
                            if (InstructorConflictList.Count == 1 && ClassRoomConflictList.Count == 0)
                            { //Just one conflict with Instructor schedule
                                ClassSessionMV.ErrorCondition = true;
                                ClassSessionMV.ErrorMessage = "Conflicts with instructor session: "
                                    + InstructorConflictList[0].StartTime.ToString() + " - " +
                                    InstructorConflictList[0].EndTime.ToString();
                                return View(ClassSessionMV);
                            }
                            else if (InstructorConflictList.Count == 0 && ClassRoomConflictList.Count == 1)
                            { //Just one conflict with Classroom schedule
                                ClassSessionMV.ErrorCondition = true;
                                ClassSessionMV.ErrorMessage = "Conflicts with class room session: "
                                    + ClassRoomConflictList[0].StartTime.ToString() + " - " +
                                    ClassRoomConflictList[0].EndTime.ToString();
                                return View(ClassSessionMV);
                            }
                            else
                            { //Multiple schedule conflicts for Instructor and/or Classroom
                                ClassSessionMV.ErrorCondition = true;
                                ClassSessionMV.ErrorMessage = "Multiple session conflicts";
                                return View(ClassSessionMV);
                            }
                        }
                    }
                    else
                    {
                        ClassSessionMV.ErrorCondition = true;
                        ClassSessionMV.ErrorMessage = "System Error: Unable to validate entry";
                        return View(ClassSessionMV);
                    }

ClassAssignmentApp/Views/ClassSessionMVC/StudentSessionsIndex.cshtml
@model ClassAssignmentApp.Models.StudentSessionMVMaint

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    string InstructorName = string.Empty;
    string DOW = string.Empty;
    string BldRoom = string.Empty;
    string CourseStatus = string.Empty;
}

<div style="margin-left:-200px; padding-bottom:20px; width:1700px; height:auto; border-style:solid; border-width:1px;">

    <div style="width:1700px; text-align:center;">
        <h3><ul>Student Class Assignment</ul></h3>
    </div>

   <form asp-action="StudentSessionsIndex" method="Post">
       <div>
            <table style="width:auto;">
                <tr>
                    <td style="width:100px; text-align:right;padding-right:5px;">
                        <label>Student:</label>
                    </td>
                    <td style="width:275px; text-align:left;">
                        <select style="width:250px; text-align:left;" class="form-select" asp-items="Model.StudentSelectList"
                                asp-for="StudentID"
                                onchange="this.form.submit()">
                            <option value="NO SELECTED VALUE">Select Student</option>
                        </select>
                    </td>

                    <td style="width:100px; text-align:right;padding-right:5px;">
                        <label>Course:</label>
                    </td>
                    <td style="width:325px; text-align:left;">
                        <select style="width:300px; text-align:left;" class="form-select" asp-items="Model.CourseSelectList"
                                asp-for="CourseID"
                                onchange="this.form.submit()">
                            @*<option value="NO SELECTED VALUE">Select Course</option>*@
                        </select>
                    </td>
                    <td style="width:400px; text-align:left; color:blue;" class="@(Model.ShowScreenMessage == true ? "display-contents" : "display-none")">
                        <span style="font-size:x-large; padding-left:250px;">@Model.ScreenMessage</span>
                    </td>
                </tr>
            </table>
       </div>

        <div style="width:auto;" class="@(Model.ShowForInput == true && Model.ShowStudentSchedule == true ? "display-contents" : "display-none")">
            <table style="width:auto; margin-left:20px; margin-top:20px;">
                <tr>
                    <td style="width:850px; text-align:left; vertical-align:top; padding-left:10px; padding-right:40px;">
                        <table style="border-style:solid; border-width:1px; width:850px;">
                            @{
                                string StudentScheduleHeading = "Student Schedule for " + Model.StudentName;
                                }
                            <thead>
                                <tr>
                                    <td colspan="7" style="text-align:center;">
                                        <b>@StudentScheduleHeading</b>
                                    </td>
                                </tr>
                                <tr>
                                    <th style="width:50px;padding:5px; border:solid; border-width:1px; border-color:saddlebrown; text-align:center;">DOW</th>
                                    <th style="width:100px;padding:5px; border:solid; border-width:1px; border-color:saddlebrown; text-align:center;">From</th>
                                    <th style="width:100px;padding:5px; border:solid; border-width:1px; border-color:saddlebrown; text-align:center;">To</th>
                                    <th style="width:250px;padding:5px; border:solid; border-width:1px; border-color:saddlebrown; text-align:center;">Course</th>
                                    <th style="width:75px;padding:5px; border:solid; border-width:1px; border-color:saddlebrown; text-align:center;">Bld/Rm</th>
                                    <th style="width:150px;padding:5px; border:solid; border-width:1px; border-color:saddlebrown; text-align:center;">Instructor</th>
                                    <th style="width:100px;padding:5px; border:solid; border-width:1px; border-color:saddlebrown; text-align:center;">Remove</th>
                                </tr>
                            </thead>


                            <tbody class="@(Model.ShowForInput == true && Model.ShowStudentSchedule == true ? "display-contents" : "display-none")">
                                @foreach (var item in Model.StudentSessions)
                                {
                                    InstructorName = item.FirstName + ' ' + item.LastName;
                                    DOW = "???";
                                    if (item.DayOfWeek == "Monday") DOW = "Mon";
                                    if (item.DayOfWeek == "Tuesday") DOW = "Tues";
                                    if (item.DayOfWeek == "Wednesday") DOW = "Wed";
                                    if (item.DayOfWeek == "Thursday") DOW = "Thu";
                                    if (item.DayOfWeek == "Friday") DOW = "Fri";
                                    if (item.DayOfWeek == "Saturday") DOW = "Sat";
                                    if (item.DayOfWeek == "Sunday") DOW = "Sun";
                                    BldRoom = item.BuildingNumber.ToString() + '/' + item.RoomNumber.ToString();

                                    <tr>
                                        <td style="padding:5px; border:solid; border-width:1px; border-color:saddlebrown;">@DOW</td>
                                        <td style="padding:5px; border:solid; border-width:1px; border-color:saddlebrown;">@item.StartTime</td>
                                        <td style="padding:5px; border:solid; border-width:1px; border-color:saddlebrown;">@item.EndTime</td>
                                        <td style="padding:5px; border:solid; border-width:1px; border-color:saddlebrown;">@item.Title</td>
                                        <td style="padding:5px; border:solid; border-width:1px; border-color:saddlebrown;">@BldRoom</td>
                                        <td style="padding:5px; border:solid; border-width:1px; border-color:saddlebrown;">@InstructorName</td>

                                        <td style="padding:5px; border:solid; border-width:1px; border-color:saddlebrown;">

                                            <input type="hidden" id="SessionKey" name="ClassSessionID" value="@item.ClassSessionID" />

                                            <a style="text-decoration-line: underline;" class="navbar-brand" asp-area="" asp-controller="ClassSessionMVC"
                                               asp-action="RemoveCourseAssignment" asp-area=""
                                               asp-route-StudentClassSessionID="@item.StudentClassSessionID"
                                               asp-route-StudentID="@Model.StudentID"
                                               onclick="return ConfirmDelete()">Remove</a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </td>
                    <td class="@(Model.ShowForInput == true && Model.ShowCourseSchedule == true ? "display-contents" : "display-none")" style="width:600px; text-align:left; vertical-align:top;">
                        <table style="border-style:solid; border-width:1px; width:600px;">
                            @{
                                 string CourseOfferingsTitle = "";

                                if (Model.CourseOfferings.Count > 0)
                                {
                                    CourseOfferingsTitle = "Offerings for Course " + Model.CourseName;
                                }
                            }
                            <thead>
                                <tr>
                                    <td colspan="6" style="text-align:center;">
                                        <b>@CourseOfferingsTitle</b>
                                    </td>
                                </tr>
                                <tr>
                                    <th style="width:50px;padding:5px; border:solid; border-width:1px; border-color:saddlebrown; text-align:center;">DOW</th>
                                    <th style="width:100px;padding:5px; border:solid; border-width:1px; border-color:saddlebrown; text-align:center;">From</th>
                                    <th style="width:100px;padding:5px; border:solid; border-width:1px; border-color:saddlebrown; text-align:center;">To</th>
                                    <th style="width:75px;padding:5px; border:solid; border-width:1px; border-color:saddlebrown; text-align:center;">Bld/Rm</th>
                                    <th style="width:150px;padding:5px; border:solid; border-width:1px; border-color:saddlebrown; text-align:center;">Instructor</th>
                                    <th style="width:100px;padding:5px; border:solid; border-width:1px; border-color:saddlebrown; text-align:center;">Select</th>
                                </tr>
                            </thead>
                            <tbody>
 
                                @foreach (var item in Model.CourseOfferings)
                                {
                                    CourseStatus = item.AvailabilityStatus;
                                    if (item.ClosedOut == "T") CourseStatus = "CLOSED";
                                    BldRoom = item.BuildingNumber.ToString() + '/' + item.RoomNumber.ToString();
                                    <tr>
                                        <td style="padding:5px; border:solid; border-width:1px; border-color:saddlebrown;">@item.DayOfWeek</td>
                                        <td style="padding:5px; border:solid; border-width:1px; border-color:saddlebrown;">@item.StartTime</td>
                                        <td style="padding:5px; border:solid; border-width:1px; border-color:saddlebrown;">@item.EndTime</td>
                                        <td style="padding:5px; border:solid; border-width:1px; border-color:saddlebrown;">@BldRoom</td>
                                        <td style="padding:5px; border:solid; border-width:1px; border-color:saddlebrown;">@item.InstructorName</td>

                                        @switch (CourseStatus)
                                        {
                                            case "SELECTED":
                                                <td class="selected" style="padding:5px; border:solid; border-width:1px; text-align:center; border-color:saddlebrown;">
                                                    SELECTED
                                                </td>
                                                break;
                                            case "CONFLICT":
                                                <td class="conflict" style="padding:5px; border:solid; border-width:1px; text-align:center; border-color:saddlebrown;">
                                                    CONFLICT
                                                </td>
                                                break;
                                            case "CLOSED":
                                                <td class="closed-out" style="padding:5px; border:solid; border-width:1px; text-align:center; border-color:saddlebrown;">
                                                    CLOSED OUT
                                                </td>
                                                break;
                                            default:
                                                <td style="padding:5px; border:solid; border-width:1px; border-color:saddlebrown; text-align:center; font-weight:600;">
                                                    <a style="text-decoration-line: underline;" class="navbar-brand" asp-area="" asp-controller="ClassSessionMVC"
                                                       asp-action="RegisterStudent" asp-area="" asp-route-StudentID="@Model.StudentID"
                                                       asp-route-ClassSessionID="@item.ClassSessionID"
                                                       asp-route-CourseID="@Model.CourseID">ADD</a>
                                                </td>
                                                break;
                                        }
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </td>
                </tr>
            </table>
        </div>
    </form>
</div>

<script type="text/javascript">
    function Confirm(action) {
        if (confirm('Are you sure?')) {
            // alert("action: " + action + @Model.WeekDay);
            // @Model.WeekDay = action + @Model.WeekDay;
            this.form.submit();
            return true;

        } else {
            return false;
        }
    }

    function ConfirmDelete() {
        if (confirm('Delete this session?')) {
            return true;
        }
        else {
            return false;
        }
    }

</script>