ClassAssignmentApp/Controllers/CourseMVCController.cs
using Microsoft.AspNetCore.Mvc;
using ClassAssignmentApp.Models;
using System.Collections.Generic;
using System.Text.Json;
using System.Net.Http.Json;
using ClassAssignmentApp.Data;
using Newtonsoft.Json;
using Microsoft.VisualBasic;
using Microsoft.AspNetCore.Mvc;
using System.Xml.Linq;

namespace ClassAssignmentApp.Controllers
{
    public class CourseMVCController : Controller
    {
        Uri baseAddress = new Uri("https://localhost:7008/api");

        private readonly HttpClient _client;

        public CourseMVCController()
        {
            _client = new HttpClient();
            _client.BaseAddress = baseAddress;
        }

        [HttpGet]
        public IActionResult Index(int? Id, string? SelectedDepartment)
        {
            CourseMVMaint CourseMV = new CourseMVMaint();
            List<Course> courseList = new List<Course>();
            CourseData CourseDataOBJ = new CourseData();

            if (TempData["CourseREC"] != null)
            {
                string MyData = TempData["CourseREC"].ToString();
                CourseData CDobj = new CourseData();
                CDobj = JsonConvert.DeserializeObject<CourseData>(MyData);
                CourseDataOBJ.CourseID = CDobj.CourseID;
                CourseDataOBJ.SelectedDepartment = CDobj.SelectedDepartment;
                CourseDataOBJ.OperationMode = CDobj.OperationMode;
                CourseDataOBJ.ErrorMessage = CDobj.ErrorMessage;
                CourseDataOBJ.ErrorCondition = CDobj.ErrorCondition;
                CourseDataOBJ.Title = CDobj.Title;
                CourseDataOBJ.Department = CDobj.Department;
                CourseDataOBJ.CreditHours = CDobj.CreditHours;
                CourseDataOBJ.PrerequisiteCourseID = CDobj.PrerequisiteCourseID;
                CourseMV.OperationMode = CourseDataOBJ.OperationMode;
                CourseMV.CourseID = CDobj.CourseID;
            }
            else
            {
                CourseMV.CourseID = 0;
                CourseDataOBJ.ErrorMessage = "";
                CourseDataOBJ.ErrorCondition = false;
            }

            HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Course").Result;
            CourseMV.Title = "";
            CourseMV.Department = "";
            CourseMV.CreditHours = 0;
            CourseMV.PrerequisiteCourseID = 0;

            if (response.IsSuccessStatusCode)
            {
                var data = response.Content.ReadAsAsync<IList<Course>>();
                CourseMV.CourseList = data.Result.ToList();

                if (SelectedDepartment != null && SelectedDepartment != "")
                {
                    var SelectedCourseData = data.Result.Where(x => x.Department == SelectedDepartment);
                    CourseMV.CourseList = SelectedCourseData.ToList();
                }
             }

            if (CourseDataOBJ != null && CourseDataOBJ.ErrorMessage != null && CourseDataOBJ.ErrorMessage.Length > 0)
            {
                CourseMV.ErrorMessage = CourseDataOBJ.ErrorMessage;
                CourseMV.ErrorCondition = true;
                CourseMV.Title = CourseDataOBJ.Title;
                CourseMV.Department = CourseDataOBJ.Department;
                CourseMV.CreditHours = CourseDataOBJ.CreditHours;
                CourseMV.PrerequisiteCourseID = CourseDataOBJ.PrerequisiteCourseID;
                CourseMV.ShowDetailsForm = true;
                return View(CourseMV);
            }
            else
                CourseMV.ErrorCondition = false;

            if (Id == null || Id == 0)
            {
                CourseMV.OperationMode = "LIST";
                CourseMV.DepatmentSelection = "";
                CourseMV.ShowDetailsForm = false;
            }
            else
            {
                if (Id == -1)
                {
                    CourseMV.ShowDetailsForm = true;
                    CourseMV.OperationMode = "ADD";
                }
                else
                {
                    HttpResponseMessage editRecord = _client.GetAsync(_client.BaseAddress + "/Course/" + Id.ToString()).Result;

                    if (editRecord.IsSuccessStatusCode)
                    {
                        var course = (Course?)editRecord.Content.ReadAsAsync<Course>().Result;

                        if (!(course == null))
                        {
                            CourseMV.CourseID = course.CourseID;
                            CourseMV.Title = course.Title;
                            CourseMV.Department = course.Department;
                            CourseMV.CreditHours = course.CreditHours;
                            CourseMV.PrerequisiteCourseID = (course.PrerequisiteCourseID == null ? 0 : course.PrerequisiteCourseID);
                            CourseMV.ShowDetailsForm = true;
                            CourseMV.OperationMode = "CHANGEDELETE";
                        }
                    }
                }
            }

            return View(CourseMV);
        }

        [HttpGet]
        public IActionResult Create(CourseMVMaint obj)
        {
            obj.ShowDetailsForm = true;
            obj.CourseID = 0;
            obj.Title = "";
            obj.Department = "";
            obj.CreditHours = 0;
            obj.PrerequisiteCourseID = 0;
            CourseMVMaint ModelObj = new CourseMVMaint();
            ModelObj.ShowDetailsForm = true;
            return View(obj);
        }

        [HttpPost]
        public IActionResult Create(Course? obj)
        {
            if (obj == null || obj.CourseID == 0 || obj.Title == "" || obj.Department == "" || obj.CreditHours == 0)
            {
                ModelState.AddModelError("Course", "Invalid data");
            }

            if (ModelState.IsValid)
            {
                //_db.DiaryEntries.Add(obj);
                //_db.SaveChanges();
                HttpResponseMessage response = _client.PostAsJsonAsync(_client.BaseAddress + "/Course/", obj).Result;

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Index",
                     new RouteValueDictionary(new
                     {
                         controller = "ErrorMessage",
                         action = "Index",
                         ErrorMessage = "Unsuccessful Add Record Attempt",
                         AddressDescription = "at Course Maintenance"
                     }));

                    //return NotFound();
                }
            }
            else
            {
                return View(obj);
            }
        }

        [HttpPost]
        public IActionResult FileUpdate(int id, CourseMVMaint MVobj, string command)
        {
            bool ErrorCondition = false;
            Course obj = new Course();
            CourseData DataOBJ = new CourseData();
            if (MVobj.CourseID != null) obj.CourseID = MVobj.CourseID;
            obj.Title = MVobj.Title;
            obj.Department = MVobj.Department;
            obj.CreditHours = (MVobj.CreditHours == null ? 0 : (int)MVobj.CreditHours);
            obj.PrerequisiteCourseID = MVobj.PrerequisiteCourseID;
            MVobj.ErrorCondition = false;
            if (obj.Title == null || obj.Title == string.Empty || obj.Title.Length < 5) ErrorCondition = true;
            if (obj.Department == null || obj.Department == string.Empty) ErrorCondition = true;
            if (obj.CreditHours == null || obj.CreditHours == 0) ErrorCondition = true;
            int ErrorCount = 0;

            switch (command)
            {
                case "Create":
                    if (ErrorCondition)
                    {
                        DataOBJ = LoadCourseDataOBJ(obj, "ADD");
                        string SER = JsonConvert.SerializeObject(DataOBJ);  //Conversion tool uses "," to separate fields and ":" to separate field/value pairs
                        TempData["CourseREC"] = SER; // Store in session value
                        return RedirectToAction("Index", new { Id = 0, SelectedDepartment = "", pCourseDataOBJ = DataOBJ });
                    }

                    if (ModelState.IsValid)
                    {
                        //_db.DiaryEntries.Add(obj);
                        //_db.SaveChanges();
                        HttpResponseMessage response = _client.PostAsJsonAsync(_client.BaseAddress + "/Course/", obj).Result;

                        if (response.IsSuccessStatusCode)
                        {
                            return RedirectToAction("Index");
                        }
                        else
                        {
                            return RedirectToAction("Index",
                             new RouteValueDictionary(new
                             {
                                 controller = "ErrorMessage",
                                 action = "Index",
                                 ErrorMessage = "Unsuccessful Add Record Attempt",
                                 AddressDescription = "at Course Maintenance"
                             }));
                            //return NotFound();
                        }
                    }
                    else
                    {
                        return View(MVobj);
                    }

                case "Edit":
                    if (ErrorCondition)
                    {
                        ModelState.AddModelError("Course", "Invalid data");
                        DataOBJ = LoadCourseDataOBJ(obj, "CHANGEDELETE");
                        string SER = JsonConvert.SerializeObject(DataOBJ);
                        TempData["CourseREC"] = SER; // Store in session value
                        return RedirectToAction("Index", new { Id = DataOBJ.CourseID, SelectedDepartment = "", pCourseDataOBJ = DataOBJ });
                    }

ClassAssignmentApp/Views/CourseMVC/FileUpdate.cshtml
@model ClassAssignmentApp.Models.CourseMVMaint

<div style="background-color:beige; border:solid; width: 1000px; height:auto; padding: 20px;">

    <table style="width:auto;">
        <tr>
            <td style="width: 900px; text-align:center;">
                <h1>ERROR PAGE</h1>
            </td>
        </tr>
    </table>

    <div style="margin-top:50px;">
        <h3>
            <span style:margin-left:100px;">
                Error: &nbsp; @Model.ErrorMessage
            </span>
        </h3>

    </div>

    <div style="margin-top:50px; margin-left:20px;">
        @if (Model.CourseID == 0) Model.CourseID = -1;

        @*@Html.ActionLink("Return to Input screen", "Index", new { Id = @Model.CourseID })*@
        <a style="text-decoration-line: underline;"
           class="navbar-brand" asp-area="" asp-controller="CourseMVC"
           asp-action="Index" asp-area=""
           asp-route-Id="@Model.CourseID">Return to Input screen</a>
    </div>
</div>

ClassAssignmentApp/Views/CourseMVC/Index.cshtml
@model ClassAssignmentApp.Models.CourseMVMaint

@{
    string buttonName = "Edit";

    switch (Model.OperationMode)
    {
        case "LIST":
            Model.ShowDetailsForm = false;
            break;

        case "CHANGEDELETE":
            Model.ShowDetailsForm = true;
            break;

        case "ADD":
            Model.ShowDetailsForm = true;
            break;

        default:
            break;
    }
}

<div style="height: auto; border:solid; padding-bottom:20px;" class="container">
    <div style="text-align:center">
        <h2>Course Maintenance</h2>
    </div>

    <form asp-action="FileUpdate" method="post">
        <table>
            <tr>
                <td>
                    <table>
                        <tr>
                            <td style="width: 200px; text-align:right; padding-right:5px;">
                                <label row="1" asp-for="SelectedDepartment" class="form-label">Selected Department:</label>
                            </td>
                            <td style="width: 100px; text-align:right; padding-bottom:2px;">
                                <input style="width:100px;" row="1" asp-for="SelectedDepartment" class="form-control" placeholder="" />
                            </td>
                            <td>
                                <button type="submit" name="command" value="Redisplay" class='btn btn-primary'>
                                    Redisplay
                                </button>
                            </td>
                        </tr>
                    </table>
                </td>

                <td style="font-weight:600">
                    @*<h4>@Html.ActionLink("Create Record", "Index", new { Id = -1 })</h4>*@
                    <a style="text-decoration-line: underline; font-size:2rem;"
                       class="navbar-brand" asp-area="" asp-controller="CourseMVC"
                       asp-action="Index" asp-area=""
                       asp-route-Id="-1">Enter New Course</a>
                </td>
            </tr>
            <tr>
                <td style="width:auto; vertical-align:top;">
                    <table>
                        <thead>
                            <tr>
                                <th style="padding:5px; border:solid; border-width:1px; border-color:saddlebrown; text-align:center;">ID</th>
                                <th style="padding:5px; border:solid; border-width:1px; border-color:saddlebrown; text-align:center;">Title</th>
                                <th style="padding:5px; border:solid; border-width:1px; border-color:saddlebrown; text-align:center;">Department</th>
                                <th style="padding:5px; border:solid; border-width:1px; border-color:saddlebrown; text-align:center;">Credit Hours</th>
                                <th style="padding:5px; border:solid; border-width:1px; border-color:saddlebrown; text-align:center;">Prereq ID</th>
                                <th style="padding:5px; border:solid; border-width:1px; border-color:saddlebrown; text-align:center;">Edit Link</th>

                            </tr>
                        </thead>

                        <tbody>
                            @foreach (var entry in Model.CourseList)
                            {
                                <tr>
                                    <td style="width: 50px; padding:5px; border:solid; border-width:1px; border-color:saddlebrown;">@entry.CourseID</td>
                                    <td style="width: 120px; padding:5px; border:solid; border-width:1px; border-color:saddlebrown;">@entry.Title</td>
                                    <td style="width: 100px; padding:5px; border:solid; border-width:1px; border-color:saddlebrown;">@entry.Department</td>
                                    <td style="width: 100px; padding:5px; border:solid; border-width:1px; border-color:saddlebrown;">@entry.CreditHours</td>
                                    <td style="width: 100px; padding:5px; border:solid; border-width:1px; border-color:saddlebrown;">@entry.PrerequisiteCourseID</td>
                                    <td style="width: 150px; padding:5px; border:solid; border-width:1px; border-color:saddlebrown;">
                                        @*@Html.ActionLink("Course Details", "Index", new { Id = @entry.CourseID })*@
                                        <a style="text-decoration-line: underline;"
                                           class="navbar-brand" asp-area="" asp-controller="CourseMVC"
                                           asp-action="Index" asp-area=""
                                           asp-route-Id="@entry.CourseID">Course details</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </td>

                <td colspan="2" class="@(Model.ShowDetailsForm == true ? "display-contents" : "display-none")">
                    <div style="margin-left:20px; height: auto; border:solid; border-color:grey; padding-top:20px; padding-bottom:20px;" class="container">
                        <div>
                            <div class="card-header bg-primary text-white">
                                <h2>Course Record</h2>
                            </div>

                            <div style="width:500px;" class="card-body">


                                <div class="form-group mb-3 label-wrap visually-hidden">
                                    <label asp-for="CourseID" class="form-label"></label>
                                    <input asp-for="CourseID" class="form-control" placeholder="" />
                                </div>

                                <div class="form-group mb-3 label-wrap">
                                    <table>
                                        <tr>
                                            <td style="width: 300px; text-align:right; padding-right:5px;">
                                                <label style="text-align:right" asp-for="Title" class="form-label">Title:</label>
                                            </td>
                                            <td style="width: 300px; text-align:right; padding-bottom:2px;">
                                                <input style="width:300px;" type="text" asp-for="Title"
                                                       value="@(Model.Title == "" ? string.Empty : Model.Title)"
                                                       class="form-control" placeholder="" />
                                                @* <span asp-validation-for="BuildingNumber" class="text-danger"></span> *@
                                            </td>
                                        </tr>
                                    </table>
                                </div>

                                <div class="form-group mb-3 label-wrap">
                                    <table>
                                        <tr>
                                            <td style="width: 300px; text-align:right; padding-right:5px;">
                                                <label style="text-align:right" asp-for="Department" class="form-label">Department:</label>
                                            </td>
                                            <td style="width: 300px; text-align:right; padding-bottom:2px;">
                                                <input style="width:300px;" type="text" asp-for="Department"
                                                       value="@(Model.Department == "" ? string.Empty : Model.Department)"
                                                       class="form-control form-control-sm" placeholder="" />
                                                @* <span asp-validation-for="RoomNumber" class="text-danger"></span> *@
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                                <div class="form-group mb-3 label-wrap">
                                    <table style="margin-left:156px;">
                                        <tr>
                                            <td style="width: 300px; text-align:right; padding-right:5px;">
                                                <label style="text-align:right; width:200px;" asp-for="CreditHours" class="form-label">Credit Hours:</label>
                                            </td>
                                            <td style="width: 300px; text-align:right; padding-bottom:2px;">
                                                <input style="width:100px;" type="number" asp-for="CreditHours"
                                                       value="@(Model.CreditHours == 0 ? string.Empty : Model.CreditHours)"
                                                       class="form-control form-control-sm" placeholder="" />
                                                @* <span asp-validation-for="Capacity" class="text-danger"></span> *@
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                                <div class="form-group mb-3 label-wrap">
                                    <table style="margin-left:156px;">
                                        <tr>
                                            <td style="width: 300px; text-align:right; padding-right:5px;">
                                                <label style="text-align:right; width:200px;" asp-for="PrerequisiteCourseID" class="form-label">Prereq ID:</label>
                                            </td>
                                            <td style="width: 300px; text-align:right; padding-bottom:2px;">
                                                <input style="width:100px;" type="number" asp-for="PrerequisiteCourseID"
                                                       value="@(Model.PrerequisiteCourseID == 0 ? string.Empty : Model.PrerequisiteCourseID)"
                                                       class="form-control form-control-sm" placeholder="" />
                                            </td>
                                        </tr>
                                    </table>
                                </div>

                                <div class="d-flex justify-content-between">
                                    <button type="submit" name="command" value="Create"
                                            class='@(Model.OperationMode == "ADD" ? "show-button" : "hide-button") btn btn-primary'
                                            onclick="return Confirm()">
                                        Add
                                    </button>
                                    &nbsp;

                                    <button type="submit" name="command" value="Edit"
                                            class='@(Model.OperationMode == "CHANGEDELETE" ? "show-button" : "hide-button") btn btn-primary'
                                            onclick="return Confirm()">
                                        Update
                                    </button>
                                    &nbsp;

                                    <button type="submit" name="command" value="Delete"
                                            class='@(Model.OperationMode == "CHANGEDELETE" ? "show-button" : "hide-button") btn btn-primary'
                                            onclick="return Confirm()">
                                        Delete
                                    </button>
                                    &nbsp;

                                    <button type="submit" name="command" value="Cancel" class='btn btn-primary'>
                                        Cancel
                                    </button>
                                </div>
                            </div>
                        </div>

                        <div style="margin-top:100px; width:500px;" class="@(Model.ErrorCondition == true ? "display-contents" : "display-none") text-danger">
                            @Model.ErrorMessage
                        </div>

                    </div>
                </td>
            </tr>
        </table>
    </form>
    <div class="table-responsive">
    </div>

</div>

<script type="text/javascript">
      function Confirm(){
          if (confirm('Are you sure?')) {
              return true;
          } else {
              return false;
          }
    }
</script>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}