ClassAssignmentApp/Controllers/ClassRoomMVCController.cs
using Microsoft.AspNetCore.Mvc;
using ClassAssignmentApp.Models;
using System.Collections.Generic;
using System.Text.Json;
using System.Net.Http.Json;
using ClassAssignmentApp.Data;
using Newtonsoft.Json;
using Microsoft.VisualBasic;

namespace ClassAssignmentApp.Controllers
{
    public class ClassRoomMVCController : Controller
    {
        Uri baseAddress = new Uri("https://localhost:7008/api");
        private readonly HttpClient _client;
        
        public ClassRoomMVCController()
        {
            _client = new HttpClient();
            _client.BaseAddress = baseAddress;
        }

        [HttpGet]
        public IActionResult Index(int? Id, int? SelectedBuildingID)
        {
            ClassRoomMVMaint ClassRoomMV = new ClassRoomMVMaint();
            List<ClassRoom> classRoomList = new List<ClassRoom>();
            ClassRoomData ClassRoomDataOBJ = new ClassRoomData();

            if (TempData["ClassRoomREC"] != null)
            {
                string MyData = TempData["ClassRoomREC"].ToString();
                ClassRoomData CDobj = new ClassRoomData();
                CDobj = JsonConvert.DeserializeObject<ClassRoomData>(MyData);
                ClassRoomDataOBJ.ClassRoomID = CDobj.ClassRoomID;
                ClassRoomDataOBJ.SelectedBuildingNo = CDobj.SelectedBuildingNo;
                ClassRoomDataOBJ.ErrorMessage = CDobj.ErrorMessage;
                ClassRoomDataOBJ.ErrorMessage = CDobj.ErrorMessage;
                ClassRoomDataOBJ.BuildingNumber = CDobj.BuildingNumber;
                ClassRoomDataOBJ.RoomNumber = CDobj.RoomNumber;
                ClassRoomDataOBJ.Capacity = CDobj.Capacity;
                ClassRoomDataOBJ.Unavailable = CDobj.Unavailable;
                ClassRoomDataOBJ.Unavail = CDobj.Unavail;
                ClassRoomMV.OperationMode = CDobj.OperationMode;
                ClassRoomMV.ClassRoomID = CDobj.ClassRoomID;
            }
            else
            {
                ClassRoomMV.ClassRoomID = 0;
                ClassRoomDataOBJ.ErrorMessage = "";
                ClassRoomDataOBJ.ErrorCondition = false;
            }

            HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/ClassRoom").Result;
            ClassRoomMV.BuildingNumber = 0;
            ClassRoomMV.RoomNumber = 0;
            ClassRoomMV.Capacity = 0;
            ClassRoomMV.Unavailable = "";

            if (response.IsSuccessStatusCode)
            {
                var data = response.Content.ReadAsAsync<IList<ClassRoom>>();
                ClassRoomMV.ClassRoomList = data.Result.ToList();

                if (SelectedBuildingID != null && SelectedBuildingID > 0)
                {
                    var SelectedBuildingData = data.Result.Where(x => x.BuildingNumber == SelectedBuildingID);
                    ClassRoomMV.ClassRoomList = SelectedBuildingData.ToList();
                }
            }

            if (ClassRoomDataOBJ != null && ClassRoomDataOBJ.ErrorMessage != null && ClassRoomDataOBJ.ErrorMessage.Length > 0)
            {
                ClassRoomMV.ErrorMessage = ClassRoomDataOBJ.ErrorMessage;
                ClassRoomMV.ErrorCondition = true;
                ClassRoomMV.RoomNumber = ClassRoomDataOBJ.RoomNumber;
                ClassRoomMV.BuildingNumber = ClassRoomDataOBJ.BuildingNumber;
                ClassRoomMV.Capacity = ClassRoomDataOBJ.Capacity;
                ClassRoomMV.Unavailable = ClassRoomDataOBJ.Unavailable;
                ClassRoomMV.ShowDetailsForm = true;
                return View(ClassRoomMV);
            }
            else
                ClassRoomMV.ErrorCondition = false;

            if (Id == null || Id == 0)
            {
                ClassRoomMV.OperationMode = "LIST";
                ClassRoomMV.BuildingNumberSelection = 0;
                ClassRoomMV.ShowDetailsForm = false;
            }
            else
            {
                if (Id == -1)
                {
                    ClassRoomMV.ShowDetailsForm = true;
                    ClassRoomMV.OperationMode = "ADD";
                }
                else
                {
                    HttpResponseMessage editRecord = _client.GetAsync(_client.BaseAddress + "/ClassRoom/" + Id.ToString()).Result;

                    if (editRecord.IsSuccessStatusCode)
                    {
                        var classRoom = (ClassRoom?)editRecord.Content.ReadAsAsync<ClassRoom>().Result;

                        if (!(classRoom == null))
                        {
                            ClassRoomMV.ClassRoomID = classRoom.ClassRoomID;
                            ClassRoomMV.BuildingNumber = classRoom.BuildingNumber;
                            ClassRoomMV.RoomNumber = classRoom.RoomNumber;
                            ClassRoomMV.Capacity = classRoom.Capacity;
                            ClassRoomMV.Unavailable = (classRoom.Unavailable == null ? "" : classRoom.Unavailable);
                            ClassRoomMV.Unavail = (classRoom.Unavailable == "T" ? true : false);
                            ClassRoomMV.ShowDetailsForm = true;
                            ClassRoomMV.OperationMode = "CHANGEDELETE";
                        }
                    }
                }
            }

            return View(ClassRoomMV);
        }

        [HttpGet]
        public IActionResult Create(ClassRoomMVMaint obj)
        {
            obj.ShowDetailsForm = true;
            obj.ClassRoomID = 0;
            obj.BuildingNumber = 0;
            obj.RoomNumber = 0;
            obj.Capacity = 0;
            obj.Unavailable = "F";

            ClassRoomMVMaint ModelObj = new ClassRoomMVMaint();
            ModelObj.ShowDetailsForm = true;
            return View(obj);
        }

        [HttpPost]
        public IActionResult Create(ClassRoom? obj)
        {
            if (obj == null || obj.ClassRoomID == 0 || obj.BuildingNumber == 0 || obj.Capacity == 0)
            {
                ModelState.AddModelError("Class Room", "Invalid data");
            }

            if (ModelState.IsValid)
            {
                //_db.DiaryEntries.Add(obj);
                //_db.SaveChanges();
                HttpResponseMessage response = _client.PostAsJsonAsync(_client.BaseAddress + "/ClassRoom/", obj).Result;

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    //return NotFound();
                    return RedirectToAction("Index",
                     new RouteValueDictionary(new
                     {
                         controller = "ErrorMessage",
                         action = "Index",
                         ErrorMessage = "Unsuccessful Add Record Attempt",
                         AddressDescription = "at Classroom Maintenance"
                     }));

                }
            }
            else
            {
                return View(obj);
            }
        }

        [HttpPost]
        public IActionResult FileUpdate(int id, ClassRoomMVMaint MVobj, string command)
        {
            bool ErrorCondition = false;
            ClassRoom obj = new ClassRoom();
            ClassRoomData DataOBJ = new ClassRoomData();

            if (MVobj.ClassRoomID != null) obj.ClassRoomID = MVobj.ClassRoomID;

            obj.BuildingNumber = MVobj.BuildingNumber;
            obj.RoomNumber = MVobj.RoomNumber;
            obj.Capacity = MVobj.Capacity;
            MVobj.ErrorCondition = false;

            if (MVobj.Unavail == true)
                obj.Unavailable = "T";
            else
                obj.Unavailable = "F";

            if (obj.BuildingNumber == null || obj.BuildingNumber == 0 || obj.BuildingNumber > 500) ErrorCondition = true;
            if (obj.RoomNumber == null || obj.RoomNumber == 0) ErrorCondition = true;
            if (obj.Capacity == null || obj.Capacity == 0) ErrorCondition = true;

            int ErrorCount = 0;

            switch (command)
            {
                case "Create":
                    if (ErrorCondition)
                    {
                        DataOBJ = LoadClassRoomDataOBJ(obj, "ADD");
                        string SER = JsonConvert.SerializeObject(DataOBJ);  //Conversion tool uses "," to separate fields and ":" to separate field/value pairs
                        TempData["ClassRoomREC"] = SER; // Store in session value
                        return RedirectToAction("Index", new { Id = 0, SelectedBuildingID = 0, pClassRoomDataOBJ = DataOBJ });
                    }

                    if (ModelState.IsValid)
                    {
                        //_db.DiaryEntries.Add(obj);
                        //_db.SaveChanges();
                        HttpResponseMessage response = _client.PostAsJsonAsync(_client.BaseAddress + "/ClassRoom/", obj).Result;

                        if (response.IsSuccessStatusCode)
                        {
                            return RedirectToAction("Index");
                        }
                        else
                        {
                            return RedirectToAction("Index",
                             new RouteValueDictionary(new
                             {
                                 controller = "ErrorMessage",
                                 action = "Index",
                                 ErrorMessage = "Unsuccessful Add Record Attempt",
                                 AddressDescription = "at Classroom Maintenance"
                             }));

                            //return NotFound();
                        }
                    }
                    else
                    {
                        return View(MVobj);
                    }


                case "Edit":
                    if (ErrorCondition)
                    {
                        ModelState.AddModelError("ClassRoom", "Invalid data");

ClassAssignmentApp/Views/ClassRoomMVC/FileUpdate.cshtml
@model ClassAssignmentApp.Models.ClassRoomMVMaint

<div style="background-color:beige; border:solid; width: 1000px; height:auto; padding: 20px;">
    
        <table style="width:auto;">
            <tr>
                <td style="width: 900px; text-align:center;">
                    <h1>ERROR PAGE</h1>
                </td>
            </tr>
        </table>

    <div style="margin-top:50px;">
        <h3>
            <span style:margin-left:100px;">
                Error: &nbsp; @Model.ErrorMessage
            </span>
        </h3>
        
    </div>

    <div style="margin-top:50px; margin-left:20px;">
        @*@Html.ActionLink("Return to Input screen", "Index", new {Id = @Model.ClassRoomID} )*@
        <a style="text-decoration-line: underline;"
           class="navbar-brand" asp-area="" asp-controller="ClassRoomMVC"
           asp-action="Index" asp-area=""
           asp-route-Id="@Model.ClassRoomID">Return to Input screen</a>
    </div>
</div>

ClassAssignmentApp/Views/ClassRoomMVC/Index.cshtml
@model ClassAssignmentApp.Models.ClassRoomMVMaint

@{
    string buttonName = "Edit";
   
    switch (Model.OperationMode)
    {
        case "LIST":
            Model.ShowDetailsForm = false;
            break;

        case "CHANGEDELETE":
            Model.ShowDetailsForm = true;
            break;

        case "ADD":
            Model.ShowDetailsForm = true;
            break;

        default:
            break;
    }
}

<div style="height: auto; border:solid; padding-bottom:20px;" class="container">
    <div style="text-align:center">
        <h2>Class Room Maintenance</h2>
    </div>

    <form asp-action="FileUpdate" method="post">
    <table>
        <tr>
            <td>
                <table>
                    <tr>
                        <td style="width: 200px; text-align:right; padding-right:5px;">
                            <label row="1" asp-for="SelectedBuildingNo" class="form-label">Selected Building No:</label>
                        </td>
                        <td style="width: 100px; text-align:right; padding-bottom:2px;">
                                <input style="width:100px;" row="1" asp-for="SelectedBuildingNo" class="form-control" placeholder="" />
                        </td>
                        <td>
                                <button type="submit" name="command" value="Redisplay" class='btn btn-primary'>
                                    Redisplay
                                </button>
                        </td>
                    </tr>
                </table>
            </td>

            <td style="font-weight:600">
                    @*<h4>@Html.ActionLink("Create Record", "Index", new { Id = -1 })</h4>*@
                <a style="text-decoration-line: underline; font-size:2rem;" 
                    class="navbar-brand" asp-area="" asp-controller="ClassRoomMVC"
                    asp-action="Index" asp-area="" 
                    asp-route-Id="-1">Enter New Classroom</a>
             </td>
         </tr>
        <tr>
            <td style="width:auto; vertical-align:top;">
                <table>
                    <thead>
                        <tr>
                            <th style="padding:5px; border:solid; border-width:1px; border-color:saddlebrown; text-align:center;">ID</th>
                            <th style="padding:5px; border:solid; border-width:1px; border-color:saddlebrown; text-align:center;">Building No</th>
                            <th style="padding:5px; border:solid; border-width:1px; border-color:saddlebrown; text-align:center;">Room No</th>
                            <th style="padding:5px; border:solid; border-width:1px; border-color:saddlebrown; text-align:center;">Maxium</th>
                            <th style="padding:5px; border:solid; border-width:1px; border-color:saddlebrown; text-align:center;">Unavailable</th>
                            <th style="padding:5px; border:solid; border-width:1px; border-color:saddlebrown; text-align:center;">Edit Link</th>

                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var entry in Model.ClassRoomList)
                        {
                            <tr>
                                <td style="width: 50px; padding:5px; border:solid; border-width:1px; border-color:saddlebrown;">@entry.ClassRoomID</td>
                                <td style="width: 120px; padding:5px; border:solid; border-width:1px; border-color:saddlebrown;">@entry.BuildingNumber</td>
                                <td style="width: 100px; padding:5px; border:solid; border-width:1px; border-color:saddlebrown;">@entry.RoomNumber</td>
                                <td style="width: 100px; padding:5px; border:solid; border-width:1px; border-color:saddlebrown;">@entry.Capacity</td>
                                <td style="width: 100px; padding:5px; border:solid; border-width:1px; border-color:saddlebrown;">@entry.Unavailable</td>
                                <td style="width: 150px; padding:5px; border:solid; border-width:1px; border-color:saddlebrown;">
                                @*@Html.ActionLink("Class Room Details", "Index", new {Id = @entry.ClassRoomID})*@
                                <a style="text-decoration-line: underline;"
                                    class="navbar-brand" asp-area="" asp-controller="ClassRoomMVC"
                                    asp-action="Index" asp-area=""
                                    asp-route-Id="@entry.ClassRoomID">Class Room details</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </td>

            <td colspan="2" class="@(Model.ShowDetailsForm == true ? "display-contents" : "display-none")">
                    <div style="margin-left:20px; height: auto; border:solid; border-color:grey; padding-top:20px; padding-bottom:20px;" class="container">
                    <div>
                        <div class="card-header bg-primary text-white">
                            <h2>Class Room Record</h2>
                        </div>

                        <div style="width:300px;" class="card-body">
                            

                                <div class="form-group mb-3 label-wrap visually-hidden">
                                    <label asp-for="ClassRoomID" class="form-label"></label>
                                    <input asp-for="ClassRoomID" class="form-control" placeholder="" />
                                </div>

                                <div class="form-group mb-3 label-wrap">
                                    <table>
                                        <tr>
                                            <td style="width: 150px; text-align:right; padding-right:5px;">
                                                <label row="1" asp-for="BuildingNumber" class="form-label">Building No:</label>
                                            </td>
                                            <td style="width: auto; text-align:right; padding-bottom:2px;">
                                                <input style="width:100px;" row="1" asp-for="BuildingNumber"
                                                    value="@(Model.BuildingNumber == 0 ? string.Empty : Model.BuildingNumber)"
                                                    class="form-control" placeholder="" />
                                                @* <span asp-validation-for="BuildingNumber" class="text-danger"></span> *@
                                            </td>
                                        </tr>
                                    </table>
                                </div>

                                <div class="form-group mb-3 label-wrap">
                                    <table>
                                        <tr>
                                            <td style="width: 150px; text-align:right; padding-right:5px;">
                                                <label asp-for="RoomNumber" class="form-label">Room No:</label>
                                            </td>
                                            <td style="width: auto; text-align:right; padding-bottom:2px;">
                                                <input style="width:100px;" asp-for="RoomNumber"
                                                       value="@(Model.RoomNumber == 0 ? string.Empty : Model.RoomNumber)"
                                                class="form-control" placeholder="" />
                                                @* <span asp-validation-for="RoomNumber" class="text-danger"></span> *@
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                                <div class="form-group mb-3 label-wrap">
                                    <table>
                                        <tr>
                                            <td style="width: 150px; text-align:right; padding-right:5px;">
                                                <label asp-for="Capacity" class="form-label">Max Capacity:</label>
                                            </td>
                                            <td style="width: auto; text-align:right; padding-bottom:2px;">
                                                <input style="width:100px;" asp-for="Capacity"
                                                       value="@(Model.Capacity == 0 ? string.Empty : Model.Capacity)"
                                                class="form-control" placeholder="" />
                                                @* <span asp-validation-for="Capacity" class="text-danger"></span> *@
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                                <div class="form-group mb-3 label-wrap">
                                    <table>
                                        <tr>
                                            <td style="width: 150px; text-align:right; padding-right:5px;">
                                                <label asp-for="Unavailable" class="form-label">Unavailable:</label>
                                            </td>


                                            <td style="width: auto; text-align:right; padding-bottom:2px;">
                                                <input class="form-check" asp-for="Unavail" type="checkbox" />
                                             </td>


                                        </tr>
                                    </table>
                                </div>

                                <div class="d-flex justify-content-between">
                                    <button type="submit" name="command" value="Create"
                                            class='@(Model.OperationMode == "ADD" ? "show-button" : "hide-button") btn btn-primary'
                                            onclick="return Confirm('add this record')">
                                            Add
                                    </button>
                                    &nbsp;

                                    <button type="submit" name="command" value="Edit"
                                            class='@(Model.OperationMode == "CHANGEDELETE" ? "show-button" : "hide-button") btn btn-primary'
                                            onclick="return Confirm('update this record')">
                                            Update
                                    </button>
                                    &nbsp;

                                    <button type="submit" name="command" value="Delete"
                                            class='@(Model.OperationMode == "CHANGEDELETE" ? "show-button" : "hide-button") btn btn-primary'
                                            onclick="return Confirm('delete this record')">
                                            Delete
                                    </button>
                                    &nbsp;

                                    <button type="submit" name="command" value="Cancel" class='btn btn-primary'>Cancel
                                    </button>
                                </div>
                        </div>
                    </div>

                    <div style="margin-top:100px; width:500px;" class="@(Model.ErrorCondition == true ? "display-contents" : "display-none") text-danger">
                            @Model.ErrorMessage
                    </div>

                </div>
            </td>
        </tr>
    </table>
    </form>
    <div class="table-responsive">

    </div>

</div>

<script type="text/javascript">
    function Confirm(question) { 
        if (confirm('Are you sure you want to ' + question + '?')) {
            return true;
        } else {
            return false;
        }
}
</script>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}